import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const viewport = 'width=device-width, initial-scale=1';

export const metadata: Metadata = {
  title: 'Daily Tamil Calendar',
  description: 'Coded by helloasir and Generated by Firebase Studio ',
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center flex-col p-4`}>        
      
        <div >
          {children}
        </div>
      </body>
    </html>
  );
}

